theme: jekyll-theme-slate
title: FPrime_MSTAR
description: Low Power Implementation of Flight Software
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
